services:
  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: "unless-stopped"
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:29092"
    depends_on:
      - kafka
  kafka:
    image: obsidiandynamics/kafka
    restart: "unless-stopped"
    ports:
      - "2181:2181"
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: "INTERNAL://kafka:29092, EXTERNAL://0.0.0.0:9092"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:29092, EXTERNAL://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT, EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_ZOOKEEPER_SESSION_TIMEOUT: "6000"
      ZOOKEEPER_AUTOPURGE_PURGE_INTERNAL: "9"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
