spring:
  application:
    name: ms-currency
  data:
    redis:
      host: localhost
      port: 6379

  currency:
    api-key: "fca_live_qG9OgrdEqoD2aj2XOnRrZn5kCmI8w5YPFIYaao8Z"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

server:
  port: 8090