spring:
  application:
    name: ms-notification-service
  kafka:
    consumer:
      group-id: ms-notification-consumer
      bootstrap-servers: "localhost:9092"
      properties:
        back.off.period: 5000
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

server:
  port: 8888



