name: Unitech-Microservices

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    name: Build and Deploy All Services
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - api-gateway
          - ms-account
          - discovery-server
          - msauth1
          - user

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./${{ matrix.service }}/gradlew

      - name: Build Service
        run: ./${{ matrix.service }}/gradlew build --stacktrace --info
        working-directory: ./${{ matrix.service }}

      - name: Verify JAR File
        run: ls -l ${{ matrix.service }}/build/libs/

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.service }}
          file: ./${{ matrix.service }}/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service }}:latest
