name: Unitech-Microservices

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Build and Test All Services
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build All Services
        run: ./gradlew build

  docker:
    name: Build and Deploy Docker Images
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew
        working-directory: api-gateway

      - name: Build Project
        run: ./gradlew api-gateway:build --stacktrace --info

      - name: Verify JAR File
        run: ls -l api-gateway/build/libs/

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image for API Gateway
        uses: docker/build-push-action@v5
        with:
          context: ./api-gateway
          file: ./api-gateway/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/api-gateway:latest

      - name: Build and Push Docker Image for Account Service
        uses: docker/build-push-action@v5
        with:
          context: ./ms-account
          file: ./ms-account/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/ms-account:latest

      - name: Build and Push Docker Image for Discovery Server
        uses: docker/build-push-action@v5
        with:
          context: ./discovery-server
          file: ./discovery-server/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/discovery-server:latest

      - name: Build and Push Docker Image for Auth Service
        uses: docker/build-push-action@v5
        with:
          context: ./msauth1
          file: ./msauth1/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/ms-auth:latest


      - name: Build and Push Docker Image for User Service
        uses: docker/build-push-action@v5
        with:
          context: ./user
          file: ./user/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/user-service:latest
